repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: python3 -m ruff check .
        language: system
        always_run: true
        pass_filenames: false
      - id: pylint
        name: pylint
        entry: python3 -m pylint src/
        language: system
        always_run: true
        pass_filenames: false
      - id: isort
        name: isort
        entry: isort .
        language: system
        always_run: true
        pass_filenames: false
      - id: autopep8
        name: autopep8
        entry: autopep8 --in-place --recursive --aggressive .
        language: system
        always_run: true
        pass_filenames: false
