version: "3.7"
services:
  streamlit:
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "src/app.py"]
